Feature/base structure
Warckut/news-list pull request #1
Opened 2024-07-12 14:17 UTC by Warckut

2024-07-12 14:18 UTC, Warckut commented
@tvivls,

2024-07-12 16:40 UTC, tvivls requested changes
по-моему не очень понятно что за src/features/news, что туда планируешь складывать?

2024-07-12 16:40 UTC, tvivls commented on src/const/routes.ts
> +  Element: any;
если как заглушка - ок
но any не используем

2024-07-12 16:40 UTC, tvivls commented on src/components/app/App.tsx
> +        <Route key={index} path={path} element={<Element {...props} />} />
оочень осторожно используй index в качестве ключа, лучше комбинировать с path

2024-07-12 16:40 UTC, tvivls commented on src/lifecycle/config.ts
> +  APP_BASE_URL: process.env.APP_BASE_URL || '/',
можно добавить еще env.example

2024-07-12 16:40 UTC, tvivls commented on .eslintrc.js
> +  overrides: [],
можно убрать?

2024-07-12 18:04 UTC, Warckut commented on src/features/news/newsSlice.ts
> +        { id: 1, title: 'news 1', content: 'content' },
Да, это я так, чтобы убедится что все правильно подключил

2024-07-12 18:08 UTC, Warckut commented on src/lifecycle/config.ts
> +  APP_BASE_URL: process.env.APP_BASE_URL || '/',
А что там должно лежать?

2024-07-15 10:20 UTC, Warckut commented
@tvivls, исправил

2024-08-02 08:38 UTC, merged